version: "3.3"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stakepool
      MYSQL_USER: stakepool
      MYSQL_PASSWORD: stakepool
