version: "3.3"

services:
  node:
    image: exccco/exchangecoin_node:latest
    ports:
     - "5666:9666"
     - "5109:9109"
    networks:
      serv:
        ipv4_address: 10.5.0.2
    working_dir: /go/bin
    command: exccd --generate --miningaddr 22u4E52pCXS6fmQpdoukwXJu8ptod1kWxa5n -u rpcuser -P rpcpass --rpclisten=0.0.0.0:9109
  wallet:
    image: exccco/exchangecoin_wallet:latest
    ports:
     - "5111:9111"
     - "5112:9110"
    networks:
      serv:
        ipv4_address: 10.5.0.3
    working_dir: /go/bin
    volumes:
      - ./tmp/.exccwallet/:/.exccwallet
    command: exccwallet -u rpcuser -P rpcpass --grpclisten=0.0.0.0:9111 --rpclisten=0.0.0.0:9110 --appdata=/.exccwallet/ --stakepoolcoldextkey=xpub6CbrWWZEcp8ioKMeje6tJoBScCMNqj2EbZemWxLF26Jiz8PQAyntBguTYDE834mPrcQJYyPxLEdzMfqSN3hbW3Hs4M9y99mZPTjKACpDsQz:10000
  stakepoold:
    image: exccco/exchangecoin_stakepoold:latest
    ports:
     - "5110:9110"
    networks:
      serv:
        ipv4_address: 10.5.0.4
    working_dir: /go/bin
    volumes:
      - ./tmp/.exccwallet/:/.exccwallet
    command: stakepoold --coldwalletextpub=xpub6CbrWWZEcp8ioKMeje6tJoBScCMNqj2EbZemWxLF26Jiz8PQAyntBguTYDE834mPrcQJYyPxLEdzMfqSN3hbW3Hs4M9y99mZPTjKACpDsQz --dbhost=localhost --dbport=3306 --dbname=stakepool --dbuser=stakepool --dbpassword=excc --exccdhost=10.5.0.2 --exccdcert=rpc.cert --exccduser=rpcuser --exccdpassword=rpcpass --wallethost=10.5.0.3 --walletcert=rpc.cert --walletuser=user --walletpassword=user --rpclisten=0.0.0.0:9110 --appdata=/.stakepoold/

networks:
  serv:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
